title: "Tinghua Chen"
author: "Tinghua Chen"
description: "Penn State University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
mathjax: true

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Tinghua_CV.pdf", title:"CV",icon =home}
  - {title:"Blog",url = "https://tinghua-chen.github.io"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "tuc579@psu.edu"}
  - {title: Github, icon: github, url: "https://tinghua-chen.github.io"}
  - {title: Tiwtter, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
